"""created tables

Revision ID: 662e08fccdb0
Revises: 3ad5e1df719c
Create Date: 2023-09-08 12:39:58.797467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662e08fccdb0'
down_revision = '3ad5e1df719c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
